version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      API_KEY: ${API_KEY:-dev-secret-key}
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/resume"
      SENTENCE_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:

